triggers:
- envs: []
  last_enabled_at: 2024-02-06 23:44:18.555969
  name: early_morning_trigger
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-02-07 05:00:00
  status: active
  variables: {}
